E UI e UI 3846 change loading on details page
hmcts/rpx-xui-approve-org pull request #585
Opened 2022-02-21 10:20 UTC by waynepHMCTS

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-3846

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-02-21 10:24 UTC, tarikdogan-hmcts approved these changes

2022-02-21 11:14 UTC, paulhowes-HMCTS requested changes
I believe the store still needs removing, although I'm happy to discuss it further if that's not the case.

2022-02-21 11:14 UTC, paulhowes-HMCTS commented on src/org-manager/components/new-pbas-info/new-pbas-info.component.html
> +    [pbaNumber]="pba" [accountName]="org.accountDetails[i] ? org.accountDetails[i].account_name : ''" [organisationId]="org ? org.organisationId : ''"
Any particular reason you've chosen the verbose route?

2022-02-21 11:14 UTC, paulhowes-HMCTS commented on src/org-manager/containers/edit-details/edit-details.component.ts
> +  public pipeScribtion: Subscription;
Typo on pipeScribtion

2022-02-21 11:14 UTC, paulhowes-HMCTS commented on src/org-manager/containers/edit-details/edit-details.component.ts
> +    private readonly store: Store<fromStore.OrganisationRootState>,
Can store be removed now we are calling direct endpoints from the service?

2022-02-21 11:14 UTC, paulhowes-HMCTS commented on src/org-manager/containers/edit-details/edit-details.component.ts
> +        } else if (!org && !this.orgId) {
We shouldn't be loading from the store anymore

2022-03-10 16:02 UTC, kuda1992 submitted a review, later dismissed
Looks good

2022-03-10 16:02 UTC, kuda1992 commented on src/org-manager/containers/edit-details/edit-details.component.spec.ts
> +fdescribe('EditDetailsComponent', () => {
Remove fdescribe

2023-08-30 07:11 UTC, closed without merging