E UI 3713 add pba to ao
hmcts/rpx-xui-approve-org pull request #600
Opened 2022-03-10 10:36 UTC by waynepHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-3713

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-03-10 12:10 UTC, johnbenjamin-hmcts requested changes

2022-03-10 12:10 UTC, johnbenjamin-hmcts commented on src/org-manager/containers/edit-details/edit-details.component.spec.ts
> +fdescribe('EditDetailsComponent', () => {
Can you change it to `describe`?

2022-03-10 16:50 UTC, johnbenjamin-hmcts submitted a review, later dismissed
Approved

2022-03-29 13:16 UTC, kuda1992 approved these changes
LGTM

2023-08-30 07:11 UTC, closed without merging