Bug/e UI 7301 under review orgs rejection
hmcts/rpx-xui-approve-org pull request #705
Opened 2022-12-08 10:17 UTC by GaryScottHMCTS

### JIRA link (if applicable) ###
[TICKET: EUI-7301](https://tools.hmcts.net/jira/browse/EUI-7301)

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-12-14 11:33 UTC, tarikdogan-hmcts submitted a review, later dismissed

2022-12-14 12:21 UTC, cogrimes submitted a review, later dismissed

2023-01-11 15:55 UTC, tarikdogan-hmcts approved these changes

2023-01-11 16:35 UTC, cogrimes approved these changes

2023-01-12 09:31 UTC, phillip-whitaker-hmcts requested changes
Please remove the TODO comments, they go against our coding standards

2023-01-12 10:16 UTC, phillip-whitaker-hmcts approved these changes

2023-01-12 10:19 UTC, merged